# Descriptief deel

In [52]:
### imports
import pandas as pd
import numpy as np

In [85]:
### data inlezen
corners = pd.read_excel("./Data/cornerballen2.xlsx")
wedstrijden = pd.read_excel("./Data/wedstrijden.xlsx")

In [86]:
### merge dataframes
df = pd.merge(corners, wedstrijden, on='wedstrijd_id', how='left')

In [55]:
df.head(10)

,schepcorner_id,wedstrijd_id,ploegnaam,ervaring_schepper,ervaring_kopper,ervaring_duo,is_thuisploeg,kwart,is_schepper_bank,is_kopper_bank,...,kop_pos_midden,kop_verplaatsen_achter,kop_veel_verplaatsen,kop_hor_verplaatsen,goal,datum,niveau,uitslag,corners_uitslag,klassement_uitslag
0,1,1,marathon,4.0,4.0,4.0,1,1,1,0,...,1,0,0,0,1,2025-03-15,4,4v1,2v1,1v5
1,2,1,marathon,4.0,4.0,4.0,1,2,0,0,...,1,0,0,0,0,2025-03-15,4,4v1,2v1,1v5
2,3,1,poba juniors,3.0,2.0,3.0,0,3,0,0,...,1,0,0,1,0,2025-03-15,4,4v1,2v1,1v5
3,4,2,mvc rudie,4.0,5.0,4.0,1,3,1,0,...,1,0,1,1,0,2024-09-03,4,11v2,2v1,8v3
4,5,2,uncle abes patty pounders,1.0,5.0,1.0,0,3,1,0,...,1,0,0,0,0,2024-09-03,4,11v2,2v1,8v3
5,6,2,uncle abes patty pounders,1.0,5.0,1.0,0,4,0,0,...,1,0,0,0,0,2024-09-03,4,11v2,2v1,8v3
6,7,3,de balzakskes,3.0,3.0,3.0,1,2,0,0,...,1,1,1,1,0,2024-09-03,4,4v6,1v1,3v10
7,8,3,spitbulls,1.0,3.0,2.0,0,2,0,0,...,1,0,1,1,1,2024-09-03,4,4v6,1v1,3v10
8,9,3,de balzakskes,3.0,3.0,3.0,1,3,0,0,...,1,0,0,0,1,2024-09-03,4,4v6,1v1,3v10
9,10,3,spitbulls,1.0,3.0,2.0,0,4,1,0,...,1,0,0,0,1,2024-09-03,4,4v6,1v1,3v10

In [56]:
df["goal"].value_counts(True)[1] * 100

61.33333333333333

#### Gescoorde corners per niveau, team, wedstrijd importance

In [57]:
### bereken percentage corners gescoord per niveau
def percentage_succesvol_per_niveau(df, niveau):
    """
    Bereken het percentage gescoorde corners per niveau.
    """
    # Filter de DataFrame op basis van het niveau
    df_niveau = df[df['niveau'] == niveau]

    # Bereken het percentage gescoorde corners
    percentage_succesvol = df_niveau["goal"].value_counts(True)[1] * 100

    print(f"Percentage gescoorde corners voor niveau {niveau}: {percentage_succesvol:.2f}%")

In [58]:
percentage_succesvol_per_niveau(df, 4)

Percentage gescoorde corners voor niveau 4: 48.84%

In [59]:
perc_per_ploeg_df = df.groupby("ploegnaam").agg({"goal": "mean", "kwart" : "count"}).reset_index()
perc_per_ploeg_df.columns = ["ploegnaam", "percentage_succesvol", "aantal_corners"]

In [60]:
df[df["ploegnaam"] == "celtic towers"]

,schepcorner_id,wedstrijd_id,ploegnaam,ervaring_schepper,ervaring_kopper,ervaring_duo,is_thuisploeg,kwart,is_schepper_bank,is_kopper_bank,...,kop_pos_midden,kop_verplaatsen_achter,kop_veel_verplaatsen,kop_hor_verplaatsen,goal,datum,niveau,uitslag,corners_uitslag,klassement_uitslag
33,34,13,celtic towers,4.0,5.0,1.0,0,3,0,1,...,1,0,0,1,0,2024-09-05,3,5v3,3v2,8v3
64,65,27,celtic towers,4.0,5.0,1.0,1,2,0,1,...,0,0,0,0,1,2024-08-29,3,5v0,1v3,NaN
65,66,27,celtic towers,4.0,5.0,1.0,1,3,0,0,...,1,0,0,0,1,2024-08-29,3,5v0,1v3,NaN

In [61]:
perc_per_ploeg_df

                    ploegnaam  percentage_succesvol  aantal_corners
0     Sunday ole tribute band              1.000000               1
1                  bbc united              0.500000               2
2               celtic towers              0.666667               3
3         cercle sportif gent              1.000000               2
4        citadel park rangers              1.000000               2
5               de balzakskes              0.500000               2
6                de coulissen              1.000000               2
7                  de leeuwen              1.000000               1
8              de schuimforel              0.000000               1
9                 enerice mvc              0.666667               3
10             expats gent fc              0.000000               1
11                 fc plateau              0.000000               2
12                 fc swakkes              1.000000               2
13               fc zatletico              1.000000               1
14               gienen druk               1.000000               1
15         het gouden hoofd a              0.000000               1
16                 lazio roma              1.000000               1
17              los galaticos              1.000000               2
18                   marathon              0.384615              13
19               mbapparte fc              0.500000               2
20                      muggi              1.000000               3
21                 mvc aardig              1.000000               1
22               mvc de hoeve              0.000000               2
23              mvc mogelijks              1.000000               2
24                  mvc muggi              1.000000               1
25               mvc recubela              0.000000               1
26                  mvc rudie              0.000000               1
27               mvc uuflakke              1.000000               1
28                       ojoo              1.000000               1
29               poba juniors              0.000000               2
30               racing sport              0.000000               1
31        reflexin cafespelen              1.000000               1
32                  spitbulls              1.000000               2
33            sporting sakowa              1.000000               1
34           surfing elephant              1.000000               1
35                   sweco fc              1.000000               1
36         t nieuw kasteeltje              1.000000               2
37               team teheran              0.000000               1
38                   tengstar              1.000000               1
39                     titans              0.000000               1
40  uncle abes patty pounders              0.000000               2
41                        vma              1.000000               1

In [62]:
df.columns

Index(['schepcorner_id', 'wedstrijd_id', 'ploegnaam', 'ervaring_schepper',
       'ervaring_kopper', 'ervaring_duo', 'is_thuisploeg', 'kwart',
       'is_schepper_bank', 'is_kopper_bank', 'score_voor',
       'schepper_pos_rechts', 'kop_pos_voor_handbal', 'kop_pos_links',
       'kop_pos_midden', 'kop_verplaatsen_achter', 'kop_veel_verplaatsen',
       'kop_hor_verplaatsen', 'goal', 'datum', 'niveau', 'uitslag',
       'corners_uitslag', 'klassement_uitslag'],
      dtype='object')

#### corner_positie

In [63]:
def positie_bepalen(row):
    """
    Bepaal de positie van de kopper voor er wordt geschept
    """
    positie = 0
    if row["kop_pos_voor_handbal"] == 1:
        if row["kop_pos_links"] == 1:
            positie = 1 
        elif row["kop_pos_midden"] == 1:
            positie = 2 
        else:
            positie = 3
    else:
        if row["kop_pos_links"] == 1:
            positie = 4 
        elif row["kop_pos_midden"] == 1:
            positie = 5 
        else:
            positie = 6

    return positie

In [69]:
def vul_kop_posities(positie):
    """
    Vul de variabelen kop_pos_voor_handbal, kop_pos_links en kop_pos_midden 
    op basis van de gegeven positie.
    """
    kop_pos_voor_handbal = 0
    kop_pos_links = 0
    kop_pos_midden = 0

    if positie == 1:
        kop_pos_links = 1
        kop_pos_voor_handbal = 1
    elif positie == 2:
        kop_pos_midden = 1
        kop_pos_voor_handbal = 1
    elif positie == 3:
        kop_pos_voor_handbal = 1
    elif positie == 4:
        kop_pos_links = 1
    elif positie == 5:
        kop_pos_midden = 1
    

    return pd.Series({"kop_pos_voor_handbal": kop_pos_voor_handbal, 
                      "kop_pos_links": kop_pos_links, 
                      "kop_pos_midden": kop_pos_midden})

In [80]:
corners_df = corners.copy()
corners_df["positie"] = corners_df.apply(positie_bepalen, axis=1)

In [82]:
corners_df.drop(columns=["kop_pos_voor_handbal", "kop_pos_links", "kop_pos_midden"], inplace=True)

In [83]:
corners_df.to_excel("./Data/cornerballen2.xlsx", index=False)

#### impact analyse

In [84]:
# strengste impact, uitkomst van 1 schepcorner in de match veranderen, is bepalend
def schepcorner_impact(df):
    results = []

    for match_id, match_data in df.groupby("wedstrijd_id"):
        uitslag_str = match_data["uitslag"].iloc[0]  # iloc selecteert eerste rij van match_data
        score_thuis, score_uit = map(int, uitslag_str.split("v"))  
        score_verschil = abs(score_thuis - score_uit)

        # Controleer of er een schepcorner is (indien alle is_thuisploeg en goal NA zijn, dan geen schepcorner)
        heeft_schepcorner = match_data["goal"].notna().any()

        if not heeft_schepcorner:
            results.append((match_id, False))  # Geen schepcorner? Geen impact.
            continue  

        # Gelijkspel: altijd impact als er een schepcorner was
        if score_thuis == score_uit:
            results.append((match_id, True))
            continue

        # Bepaal winnaar en verliezer
        if score_thuis > score_uit:
            winnaar = 1
            verliezer = 0
        else:
            winnaar = 0
            verliezer = 1

        # Controleer of winnaar minstens Ã©Ã©n schepcorner scoorde
        winnaar_heeft_gescoord = ((match_data["is_thuisploeg"] == winnaar) & (match_data["goal"] == 1)).any()

        # Controleer of verliezer minstens Ã©Ã©n schepcorner miste
        verliezer_heeft_gemist = ((match_data["is_thuisploeg"] == verliezer) & (match_data["goal"] == 0)).any()

        # Strikte voorwaarde: maximaal 1 verschil en schepcorner moet impact hebben
        if score_verschil == 1 and (winnaar_heeft_gescoord or verliezer_heeft_gemist):
            results.append((match_id, True))
        else:
            results.append((match_id, False))

    return pd.DataFrame(results, columns=["wedstrijd_id", "schepcorner_impact"])

In [87]:
schepcorner_impact_df = schepcorner_impact(df)

In [88]:
schepcorner_impact_df

    wedstrijd_id  schepcorner_impact
0              1               False
1              2               False
2              3               False
3              4               False
4              5               False
5              6                True
6              7               False
7              8               False
8              9               False
9             10               False
10            11               False
11            12                True
12            13               False
13            14               False
14            15               False
15            16                True
16            17               False
17            18                True
18            19               False
19            20               False
20            21               False
21            22               False
22            23               False
23            24               False
24            25               False
25            26                True
26            27               False
27            28               False
28            29                True
29            30                True
30            31               False

In [ ]:
### percentage van wedstrijden waarbij 1 schepcorner tijdens de match bepalend was
schepcorner_impact_df["schepcorner_impact"].sum()/schepcorner_impact_df.shape[0]

0.22580645161290322

In [92]:
def bepaal_winnaar_verliezer(uitslag_str):
    thuis_score, uit_score = map(int, uitslag_str.split('v'))
    
    if thuis_score > uit_score:
        return 1, 0  
    elif uit_score > thuis_score:
        return 0, 1  
    else:
        return None, None

In [93]:
# Functie om schepcorner-impact te bepalen
def impact_alle_schepcorners_gemist(uitslag_str, match_data):
    # Bepaal het aantal schepcorner-goals per ploeg
    schepcorner_goals_thuis = match_data[match_data["is_thuisploeg"] == 1]["goal"].sum()
    schepcorner_goals_uit = match_data[match_data["is_thuisploeg"] == 0]["goal"].sum()
    
    # Bereken nieuwe uitslag zonder schepcorners
    thuis_score, uit_score = map(int, uitslag_str.split('v'))
    thuis_score -= schepcorner_goals_thuis
    uit_score -= schepcorner_goals_uit

    # Bepaal de oorspronkelijke en nieuwe winnaar
    oorspronkelijke_winnaar = bepaal_winnaar_verliezer(uitslag_str)
    nieuwe_winnaar = bepaal_winnaar_verliezer(f"{thuis_score}v{uit_score}")
    
    # Schepcorner heeft impact als de winnaar verandert
    return oorspronkelijke_winnaar != nieuwe_winnaar

In [94]:
impact_resultaten = df.groupby("wedstrijd_id").apply(
    lambda match_data: impact_alle_schepcorners_gemist(match_data["uitslag"].iloc[0], match_data)
)

C:\Users\cosyn\AppData\Local\Temp\ipykernel_24712\2269804217.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  impact_resultaten = df.groupby("wedstrijd_id").apply(

In [100]:
impact_resultaten.sum()/impact_resultaten.shape[0]  # percentage van wedstrijden waarbij 1 schepcorner tijdens de match bepalend was

0.0967741935483871

In [ ]:
# impact schepcorner moest elke schepcorner gescoord worden
def impact_alle_schepcorners_gescoord(uitslag_str, match_data):
    # tel het aantal gemiste corners per team
    gemiste_schepcorners_thuis = ((match_data["is_thuisploeg"] == 1) & (match_data["goal"] == 0)).sum()
    gemiste_schepcorners_uit = ((match_data["is_thuisploeg"] == 0) & (match_data["goal"] == 0)).sum()

    # Bereken nieuwe uitslag als alle schepcorners gescoord waren
    thuis_score, uit_score = map(int, uitslag_str.split('v'))
    thuis_score += gemiste_schepcorners_thuis  # Voeg alleen gemiste schepcorners toe
    uit_score += gemiste_schepcorners_uit

    # Bepaal oorspronkelijke en nieuwe winnaar
    oorspronkelijke_winnaar = bepaal_winnaar_verliezer(uitslag_str)
    nieuwe_winnaar = bepaal_winnaar_verliezer(f"{thuis_score}v{uit_score}")

    # Schepcorner heeft impact als de winnaar verandert
    return oorspronkelijke_winnaar != nieuwe_winnaar

In [ ]:
def heeft_schepcorner_impact_mild(uitslag_str, match_data):

    # Tel gescoorde en gemiste schepcorners per team
    gescoorde_schepcorners_thuis = ((match_data["is_thuisploeg"] == 1) & (match_data["goal"] == 1)).sum()
    gemiste_schepcorners_thuis = ((match_data["is_thuisploeg"] == 1) & (match_data["goal"] == 0)).sum()
    
    gescoorde_schepcorners_uit = ((match_data["is_thuisploeg"] == 0) & (match_data["goal"] == 1)).sum()
    gemiste_schepcorners_uit = ((match_data["is_thuisploeg"] == 0) & (match_data["goal"] == 0)).sum()
    
    # Huidige score bepalen
    thuis_score, uit_score = map(int, uitslag_str.split('v'))
    oorspronkelijke_winnaar = bepaal_winnaar_verliezer(uitslag_str)
    
    # Als het gelijkspel was en er waren schepcorners, dan heeft het impact
    if oorspronkelijke_winnaar is None and (gescoorde_schepcorners_thuis + gescoorde_schepcorners_uit + gemiste_schepcorners_thuis + gemiste_schepcorners_uit) > 0:
        return True
    
    # Bepaal de minimale score van de oorspronkelijke winnaar en de maximale score van de verliezer
    if oorspronkelijke_winnaar == 1:
        min_winnaar_score = thuis_score - gescoorde_schepcorners_thuis
        max_verliezer_score = uit_score + gemiste_schepcorners_uit
    else:
        min_winnaar_score = uit_score - gescoorde_schepcorners_uit
        max_verliezer_score = thuis_score + gemiste_schepcorners_thuis

    # Nieuwe uitslag bepalen zonder schepcorners
    nieuwe_winnaar = bepaal_winnaar_verliezer(f"{min_winnaar_score}v{max_verliezer_score}")
    
    # Impact als de winnaar verandert
    return oorspronkelijke_winnaar != nieuwe_winnaar